import Header from "@/components/Layout/Header";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { virtualArray } from "@/utils/VirtualArray";
import Comic from "@/components/ComicCard";
import { AiOutlineArrowRight } from "react-icons/ai";
import axios from "axios";
import Pagination from "@/components/Pagination";
import Footer from "@/components/Layout/Footer";

export async function getServerSideProps(context) {
  const page = context.query.page || 1;
  try {
    const {
      data: { comics: comics, total_pages: totalPages },
    } = await axios.get(
      "https://comics-api-kensine.vercel.app/latest?page=" + page
    );

    return { props: { comics, totalPages } };
  } catch (error) {
    console.error("Error fetching data:", error.message);
    return { data: [] };
  }
}

const Page = (props) => {
  const router = useRouter();
  const page = Number(router.query.page || 1);
  const comics = props.comics;
  const title = "Last Update - Page " + page;
  const totalPages = props.totalPages;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main>
        <div className="latest-update py-3 px-2 bg-white">
          <div className="max-w-7xl mx-auto">
            <h2 className="text-xl my-2 font-bold">
              Latest update - Page {page}
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-5">
              {comics?.map((item, index) => {
                return <Comic key={index} data={item} />;
              })}
            </div>
            <Pagination
              path={`page`}
              currentPage={page}
              totalPages={totalPages}
            />
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Page;
